name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [created]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Uncomment when you have tests
      # - name: Run tests
      #   run: npm test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-node-${{ matrix.node-version }}
          path: dist/

  release:
    needs: build
    # Removing condition temporarily to ensure job runs
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-node-20.x
          path: dist/

      - name: Install pkg
        run: npm install -g pkg

      - name: Install dependencies
        run: npm ci

      - name: Create executables
        run: |
          mkdir -p executables
          pkg . --out-path=executables --targets=node16-linux-x64,node16-macos-x64,node16-win-x64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            executables/*
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        # Add --access=public to allow publishing scoped packages
        run: |
          echo "Attempting to publish package as a scoped package"
          npm config list
          npm publish --access=public || echo "Package publish failed, but continuing workflow"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
